@startuml "Sequence Diagram"
skinparam style strictuml
participant ProcessHistorian
== Initialization ==
activate ProcessHistorian
ProcessHistorian -> "[ConfigBuilder]\nConfigurator" as ConfigBuilder.Configurator ** : create
deactivate ProcessHistorian
activate ConfigBuilder.Configurator
ConfigBuilder.Configurator -> "[ConfigBuilder]\nSPARQLClient" as ConfigBuilder.SPARQLClient ** : create
ConfigBuilder.Configurator -> ConfigBuilder.SPARQLClient : fetch data
deactivate ConfigBuilder.Configurator
activate ConfigBuilder.SPARQLClient
ConfigBuilder.SPARQLClient -> ConfigBuilder.Configurator : return data
deactivate ConfigBuilder.SPARQLClient
activate ConfigBuilder.Configurator
ConfigBuilder.Configurator -> ConfigBuilder.Configurator : write config
ConfigBuilder.Configurator -> ConfigBuilder.SPARQLClient !! : delete
deactivate ConfigBuilder.Configurator
activate ProcessHistorian
ProcessHistorian -> ConfigBuilder.Configurator !! : delete

ProcessHistorian -> "[OPCUAClient]\nClient" as OPCUAClient.Client ** : create
activate OPCUAClient.Client
deactivate ProcessHistorian
OPCUAClient.Client -> "[OPCUAClient]\nSubscriptionHandler" as OPCUAClient.SubscriptionHandler ** : create
deactivate OPCUAClient.Client

activate ProcessHistorian
ProcessHistorian -> "[CloudBuffer]\nBuffer" as CloudBuffer.Buffer ** : create
activate CloudBuffer.Buffer
deactivate ProcessHistorian
CloudBuffer.Buffer -> "[CloudBuffer]\nInfluxDBClient" as CloudBuffer.InfluxDBClient ** : create
deactivate CloudBuffer.Buffer
...

== Polling ==

OPCUAClient.Client -> OPCUAClient.Client : timer event
activate OPCUAClient.Client
OPCUAClient.Client -> OPCUAClient.Client : poll data
OPCUAClient.Client -> ProcessHistorian : send data
activate ProcessHistorian
deactivate OPCUAClient.Client
ProcessHistorian -> CloudBuffer.Buffer : add data
activate CloudBuffer.Buffer
deactivate CloudBuffer.Buffer
deactivate ProcessHistorian
CloudBuffer.Buffer -> CloudBuffer.Buffer : timer event
activate CloudBuffer.Buffer
CloudBuffer.Buffer -> CloudBuffer.InfluxDBClient : send data
deactivate CloudBuffer.Buffer
...

== Subscription ==

OPCUAClient.SubscriptionHandler -> OPCUAClient.SubscriptionHandler : data incomming
activate OPCUAClient.SubscriptionHandler
OPCUAClient.SubscriptionHandler -> OPCUAClient.SubscriptionHandler : get data
OPCUAClient.SubscriptionHandler -> ProcessHistorian : send data
activate ProcessHistorian
deactivate OPCUAClient.SubscriptionHandler
ProcessHistorian -> CloudBuffer.Buffer : add data
activate CloudBuffer.Buffer
deactivate CloudBuffer.Buffer
deactivate ProcessHistorian
CloudBuffer.Buffer -> CloudBuffer.Buffer : timer event
activate CloudBuffer.Buffer
CloudBuffer.Buffer -> CloudBuffer.InfluxDBClient : send data
deactivate CloudBuffer.Buffer
...
@enduml