@startjson "OPC UA Config"
{
  "host": "url",
  "sensors": [
    {
      "attributes": [
        {
          "intervall": "number",
          "mode": ["\"poll\"", "\"subscription\""],
          "name": "string",
          "namespace": "string",
          "node_identifier": "string"
        }
      ],
      "id": "string"
    }
  ],
  "actuators": [
    {
      "attributes": [
        {
          "intervall": "number",
          "mode": ["\"poll\"", "\"subscription\""],
          "name": "string",
          "namespace": "string",
          "node_identifier": "string"
        }
      ],
      "id": "string"
    }
  ],
  "services": [
    {
      "attributes": [
        {
          "intervall": "number",
          "mode": ["\"poll\"", "\"subscription\""],
          "name": "string",
          "namespace": "string",
          "node_identifier": "string"
        }
      ],
      "id": "string"
    }
  ]
}

@endjson
