@startjson "Program Config"
{
    "include": ["\"sensors\"", "\"actuators\"", "\"services\""],
    "tripleStore": {
        "host": "url",
        "username": "string",
        "password": "string"
    },
    "influxdb": {
        "host": "url",
        "token": "string",
        "organization": "string",
        "bucket": "string"
    },
    "buffer": {
        "size": "number",
        "push_interval": "number"
    },
    "heartbeat_interval": "number"
}
@endjson