@startuml "Sequence Diagram"
skinparam style strictuml
participant ProcessHistorian
participant "OPC UA\nPoll Thread" as PollThread
participant "CloudBuffer\nPush Thread" as PushThread
== Initialization ==
activate ProcessHistorian
ProcessHistorian -> "[ConfigBuilder]\nConfigurator" as ConfigBuilder.Configurator ** : create
deactivate ProcessHistorian
activate ConfigBuilder.Configurator
ConfigBuilder.Configurator -> "[ConfigBuilder]\nSPARQLClient" as ConfigBuilder.SPARQLClient ** : create
ConfigBuilder.Configurator -> ConfigBuilder.SPARQLClient : fetch data
deactivate ConfigBuilder.Configurator
activate ConfigBuilder.SPARQLClient
ConfigBuilder.SPARQLClient -> ConfigBuilder.Configurator : return data
deactivate ConfigBuilder.SPARQLClient
activate ConfigBuilder.Configurator
ConfigBuilder.Configurator -> ConfigBuilder.Configurator : write config
ConfigBuilder.Configurator -> ConfigBuilder.SPARQLClient !! : delete
deactivate ConfigBuilder.Configurator
activate ProcessHistorian
ProcessHistorian -> ConfigBuilder.Configurator !! : delete

ProcessHistorian -> "[CloudBuffer]\nBuffer" as CloudBuffer.Buffer ** : create
activate CloudBuffer.Buffer
deactivate ProcessHistorian
CloudBuffer.Buffer -> "[CloudBuffer]\nInfluxDBClient" as CloudBuffer.InfluxDBClient ** : create
deactivate CloudBuffer.Buffer

activate ProcessHistorian
ProcessHistorian -> "[OPCUAClient]\nClient" as OPCUAClient.Client ** : create
activate OPCUAClient.Client
deactivate ProcessHistorian
OPCUAClient.Client -> OPCUAClient.Client : parse config
OPCUAClient.Client -> "[OPCUAClient]\nSubscriptionHandler" as OPCUAClient.SubscriptionHandler ** : create
deactivate OPCUAClient.Client

activate ProcessHistorian
ProcessHistorian -> PollThread ** : create worker\nthreads
ProcessHistorian -> PushThread ** : create worker\nthread
deactivate ProcessHistorian
...

== Polling ==

PollThread -> PollThread : timer event
activate PollThread
PollThread -> OPCUAClient.Client : poll data
activate OPCUAClient.Client
OPCUAClient.Client -> OPCUAClient.Client : poll data
OPCUAClient.Client ->  CloudBuffer.Buffer : add data
activate CloudBuffer.Buffer
deactivate CloudBuffer.Buffer
deactivate OPCUAClient.Client
deactivate PollThread

PushThread -> PushThread : timer event
activate PushThread
PushThread -> CloudBuffer.Buffer : call push function
activate CloudBuffer.Buffer
CloudBuffer.Buffer -> CloudBuffer.InfluxDBClient : send data
deactivate CloudBuffer.Buffer
deactivate PushThread
...

== Subscription ==

OPCUAClient.SubscriptionHandler -> OPCUAClient.SubscriptionHandler : data incoming
activate OPCUAClient.SubscriptionHandler
OPCUAClient.SubscriptionHandler -> OPCUAClient.SubscriptionHandler : get data
OPCUAClient.SubscriptionHandler -> CloudBuffer.Buffer : add data
activate CloudBuffer.Buffer
deactivate CloudBuffer.Buffer
deactivate OPCUAClient.SubscriptionHandler

PushThread -> PushThread : timer event
activate PushThread
PushThread -> CloudBuffer.Buffer : call push function
activate CloudBuffer.Buffer
CloudBuffer.Buffer -> CloudBuffer.InfluxDBClient : send data
deactivate CloudBuffer.Buffer
deactivate PushThread
...
@enduml