@startgantt "Gantt Diagramm Part 1"
Project starts the 2021-04-13

[Vorlesungsstart] happens at 2021-04-13
[Projekt Kickoff] happens at 2021-04-21
[Selbststudium] starts at 2021-04-21
[Zwischenpräsentation] happens at 2021-05-19

[Projekt Kickoff] displays on same row as [Vorlesungsstart]
[Zwischenpräsentation] displays on same row as [Vorlesungsstart]

[Selbststudium] lasts 7 days
[Problemanalyse] lasts 14 days
[Architekturplanung] lasts 14 days
[Theoriearbeit] lasts 14 days
[Dokumentation] lasts 14 days
[Bericht] lasts 7 days

[Problemanalyse] starts at [Selbststudium]'s end
[Architekturplanung] starts at [Selbststudium]'s end
[Theoriearbeit] starts at [Selbststudium]'s end
[Dokumentation] starts at [Selbststudium]'s end

[Bericht] starts at [Dokumentation]'s end
@endgantt