name: Render PlantUML Diagrams
on:
  push:
    branches:
      - main
jobs:
  render_plantuml:
    runs-on: ubuntu-latest
    name: Render PlantUML
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Render 
        id: plantuml
        uses: grassedge/generate-plantuml-action@master
        with:
          path: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
